CREATE TABLE ES.SharedContent
(
	Id INT IDENTITY(1,1) CONSTRAINT PK_ES_SharedContent PRIMARY KEY CLUSTERED,
	Content NVARCHAR(MAX) NULL,
	Modified DATETIMEOFFSET(0) NOT NULL,
	Created DATETIMEOFFSET(0) NOT NULL,
);
